services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ocms-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - ocms
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: ocms-web
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - ocms
        depends_on:
            - app

    db:
        image: mariadb:11
        container_name: ocms-db
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: webtiptop
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - ocms

volumes:
    dbdata:

networks:
    ocms:
